[package]
name = "cryprice"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
colored = "3.0.0"
hyperliquid_rust_sdk = "0.5.0"
log = "0.4.27"
pretty-table = "0.1.3"
thin-logger = "0.1.0"
tokio = { version = "1.44.2", features = ["full"] }
